// Generated by gencpp from file ian_bot/PWMfreqResponse.msg
// DO NOT EDIT!


#ifndef IAN_BOT_MESSAGE_PWMFREQRESPONSE_H
#define IAN_BOT_MESSAGE_PWMFREQRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ian_bot
{
template <class ContainerAllocator>
struct PWMfreqResponse_
{
  typedef PWMfreqResponse_<ContainerAllocator> Type;

  PWMfreqResponse_()
    : actual_freq(0)  {
    }
  PWMfreqResponse_(const ContainerAllocator& _alloc)
    : actual_freq(0)  {
  (void)_alloc;
    }



   typedef uint16_t _actual_freq_type;
  _actual_freq_type actual_freq;





  typedef boost::shared_ptr< ::ian_bot::PWMfreqResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ian_bot::PWMfreqResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PWMfreqResponse_

typedef ::ian_bot::PWMfreqResponse_<std::allocator<void> > PWMfreqResponse;

typedef boost::shared_ptr< ::ian_bot::PWMfreqResponse > PWMfreqResponsePtr;
typedef boost::shared_ptr< ::ian_bot::PWMfreqResponse const> PWMfreqResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ian_bot::PWMfreqResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ian_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ian_bot': ['/home/ubuntu/catkin_ws/src/ian_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ian_bot::PWMfreqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ian_bot::PWMfreqResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ian_bot::PWMfreqResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1988e52f9fdbbcf3e1c6fbb44e3e57a";
  }

  static const char* value(const ::ian_bot::PWMfreqResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1988e52f9fdbbcfULL;
  static const uint64_t static_value2 = 0x3e1c6fbb44e3e57aULL;
};

template<class ContainerAllocator>
struct DataType< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ian_bot/PWMfreqResponse";
  }

  static const char* value(const ::ian_bot::PWMfreqResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
uint16 actual_freq\n\
\n\
";
  }

  static const char* value(const ::ian_bot::PWMfreqResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actual_freq);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWMfreqResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ian_bot::PWMfreqResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ian_bot::PWMfreqResponse_<ContainerAllocator>& v)
  {
    s << indent << "actual_freq: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.actual_freq);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAN_BOT_MESSAGE_PWMFREQRESPONSE_H
