// Generated by gencpp from file ian_bot/PWMget.msg
// DO NOT EDIT!


#ifndef IAN_BOT_MESSAGE_PWMGET_H
#define IAN_BOT_MESSAGE_PWMGET_H

#include <ros/service_traits.h>


#include <ian_bot/PWMgetRequest.h>
#include <ian_bot/PWMgetResponse.h>


namespace ian_bot
{

struct PWMget
{

typedef PWMgetRequest Request;
typedef PWMgetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PWMget
} // namespace ian_bot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ian_bot::PWMget > {
  static const char* value()
  {
    return "7e4c244c821737a5d9e99b63cbe39052";
  }

  static const char* value(const ::ian_bot::PWMget&) { return value(); }
};

template<>
struct DataType< ::ian_bot::PWMget > {
  static const char* value()
  {
    return "ian_bot/PWMget";
  }

  static const char* value(const ::ian_bot::PWMget&) { return value(); }
};


// service_traits::MD5Sum< ::ian_bot::PWMgetRequest> should match 
// service_traits::MD5Sum< ::ian_bot::PWMget > 
template<>
struct MD5Sum< ::ian_bot::PWMgetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ian_bot::PWMget >::value();
  }
  static const char* value(const ::ian_bot::PWMgetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ian_bot::PWMgetRequest> should match 
// service_traits::DataType< ::ian_bot::PWMget > 
template<>
struct DataType< ::ian_bot::PWMgetRequest>
{
  static const char* value()
  {
    return DataType< ::ian_bot::PWMget >::value();
  }
  static const char* value(const ::ian_bot::PWMgetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ian_bot::PWMgetResponse> should match 
// service_traits::MD5Sum< ::ian_bot::PWMget > 
template<>
struct MD5Sum< ::ian_bot::PWMgetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ian_bot::PWMget >::value();
  }
  static const char* value(const ::ian_bot::PWMgetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ian_bot::PWMgetResponse> should match 
// service_traits::DataType< ::ian_bot::PWMget > 
template<>
struct DataType< ::ian_bot::PWMgetResponse>
{
  static const char* value()
  {
    return DataType< ::ian_bot::PWMget >::value();
  }
  static const char* value(const ::ian_bot::PWMgetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // IAN_BOT_MESSAGE_PWMGET_H
