// Generated by gencpp from file ian_bot/PWMgetResponse.msg
// DO NOT EDIT!


#ifndef IAN_BOT_MESSAGE_PWMGETRESPONSE_H
#define IAN_BOT_MESSAGE_PWMGETRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ian_bot
{
template <class ContainerAllocator>
struct PWMgetResponse_
{
  typedef PWMgetResponse_<ContainerAllocator> Type;

  PWMgetResponse_()
    : duty(0)  {
    }
  PWMgetResponse_(const ContainerAllocator& _alloc)
    : duty(0)  {
  (void)_alloc;
    }



   typedef uint8_t _duty_type;
  _duty_type duty;





  typedef boost::shared_ptr< ::ian_bot::PWMgetResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ian_bot::PWMgetResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PWMgetResponse_

typedef ::ian_bot::PWMgetResponse_<std::allocator<void> > PWMgetResponse;

typedef boost::shared_ptr< ::ian_bot::PWMgetResponse > PWMgetResponsePtr;
typedef boost::shared_ptr< ::ian_bot::PWMgetResponse const> PWMgetResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ian_bot::PWMgetResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ian_bot::PWMgetResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ian_bot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ian_bot': ['/home/ian/catkin_ws/src/ian_bot/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ian_bot::PWMgetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ian_bot::PWMgetResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ian_bot::PWMgetResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9191ddc0c0b64448b0d2ca747dd200b";
  }

  static const char* value(const ::ian_bot::PWMgetResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9191ddc0c0b6444ULL;
  static const uint64_t static_value2 = 0x8b0d2ca747dd200bULL;
};

template<class ContainerAllocator>
struct DataType< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ian_bot/PWMgetResponse";
  }

  static const char* value(const ::ian_bot::PWMgetResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
uint8 duty\n\
\n\
";
  }

  static const char* value(const ::ian_bot::PWMgetResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duty);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PWMgetResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ian_bot::PWMgetResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ian_bot::PWMgetResponse_<ContainerAllocator>& v)
  {
    s << indent << "duty: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.duty);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IAN_BOT_MESSAGE_PWMGETRESPONSE_H
